services:
  - type: web
    name: image-export-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main.py --timeout 300
    envVars:
      - key: DROPBOX_ACCESS_TOKEN
        sync: false
      - key: SHARED_FOLDER_PATH
        sync: false
